language: go

go:
  - 1.11
  - master

install:
  # Prevent default install task that does a `go get -t ./...`
  - true

before_install:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - make test
