---
applications:
- name: metric-exporter
  memory: 100M
  instances: 1
  buildpacks:
    - go_buildpack
  env:
    GOPACKAGENAME: github.com/alphagov/paas-metric-exporter
    ENABLE_STATSD: false
    ENABLE_PROMETHEUS: true
